# Helix AI discord Bot Lavalink Dockerfile

# base image
FROM azul/zulu-openjdk:13

# Run as non-root user
RUN groupadd -g 322 lavalink && \
    useradd -r -u 322 -g lavalink lavalink
USER lavalink

# Work Directory
WORKDIR /Lavalink

# open ports
EXPOSE 2333:2333

#copy file directory
COPY Lavalink.jar Lavalink.jar
COPY application.yml application.yml

# start Docker image for discord bot docker build -t sinless777/helix_bot .
CMD ["java", "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2", "-jar", "Lavalink.jar"]