CREATE DATABASE Helix_Stats;

CREATE TABLE Liscense_Keys (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	Client_ID BIGINT,
    License_Key VARCHAR(20) UNIQUE,
    Active_Status VARCHAR(8),
	Date_Created DATE, 
	Date_Activated DATE,
	Last_CheckIN DATETIME,
	Clients_using BIGINT(10)
);
CREATE TABLE CLIENTS (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    DATE_PURCHASED DATE,
    Real_NAME VARCHAR(100),
	Discord_Name VARCHAR(100),
	Email VARCHAR(200),
	Verified_Email VARCHAR(5),
	Verified VARCHAR(5),
    Liscene_Key VARCHAR(20),
	Public_IP VARCHAR(25) UNIQUE
);
CREATE TABLE STATS (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    DISCORD_GUILD VARCHAR(150),
    Discord_User VARCHAR(100),
    LICENSE_KEY VARCHAR(24) UNIQUE,
	QUERY_Count BIGINT,
	QUERY_Average BIGINT,
	NOTES VARCHAR(2000)
);
CREATE TABLE Website (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    Website VARCHAR(50),
    Website_URL VARCHAR(100)
);