# Helix AI discord Bot Dockerfile

# base image
FROM python:3.10.0b4

# Work Directory
WORKDIR /Helix

# Copy Requirments text file
COPY requirements.txt ./

# open ports
EXPOSE 3306:3306
EXPOSE 443:443
EXPOSE 50000-65535:50000-65535

# Upgrade pip
# install py audio
# install requirements.txt
RUN apt-get update
RUN pip install --no-cache-dir --upgrade pip
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
Run pip install pyaudio
RUN pip install -r requirements.txt

RUN apt-get install -y ffmpeg

#copy file directory
COPY . .

# start Docker image for discord bot
CMD ["python", "bot.py"]