# Generated by Django 4.0.4 on 2022-05-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
