# Helix AI discord Bot Dockerfile

# base image
FROM ubuntu:20.04

# Work Directory
WORKDIR /Discord

# Copy Requirments text file
COPY requirements.txt ./

# open ports
EXPOSE 3306:3306
EXPOSE 443:443
EXPOSE 2333:2333
EXPOSE 50000-65535:50000-65535

# Upgrade pip
# install py audio
# install requirements.txt
RUN apt-get update
RUN pip install --no-cache-dir --upgrade pip
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
Run pip install pyaudio
RUN pip install -r requirements.txt
RUN pip install --upgrade youtube-dl
RUN wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl
RUN apt-get install -y ffmpeg

#copy file directory
COPY . .

# start Docker image for discord botdocker build -t sinless777/helix_bot .
CMD ["java", "-jar", "openjdk-13.0.2_windows-x64_bin/jdk-13.0.2/bin/lavalink.jar"]
CMD ["python", "main.py"]