# Helix AI discord Bot Dockerfile

# base image
FROM nikolaik/python-nodejs:python3.9-nodejs17

# Work Directory
WORKDIR /Discord

# Copy Requirments text file
COPY requirements.txt ./

# open ports
EXPOSE 3306:3306
EXPOSE 443:443
EXPOSE 2333:2333
EXPOSE 50000-65535:50000-65535


# Upgrade pip
RUN apt-get update
RUN pip install --no-cache-dir --upgrade pip
# Upgrade pip
# install py audio
# install requirements.txt
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
RUN pip install pyaudio
RUN pip install -r requirements.txt
RUN apt-get install -y ffmpeg

#copy file directory
COPY . .

# start Docker image for discord bot docker build -t sinless777/helix_bot .
CMD ["python", "main.py"]