name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thankyou for reporting your very first issue with Helix, we will get to you as soon as possible.'
        pr-message: 'Thankyou for reporting your very first pull request with Helix, we will get to you as soon as possible.'
